#!/bin/sh

for dir in ~/dev/pixformance/*/
do
  cd $dir
  if git rev-parse --git-dir > /dev/null 2>&1; then

    log=$(git log --pretty=format:"%s" --reverse --branches --since=1.week.ago --author=George)

    if [ -n "$log" ]; then
      echo "$dir"
      echo "$log"
      echo
    fi
  fi
done
