#!/bin/sh

all_authors=$(git log --format='%aN' | sort -u)
num_authors=0

while read author
do
  if [ -z "$1" ]; then
    res=$(git log --name-only --author="$author" --pretty=format: $(git ls-files) | sed '/^\s*$/d' | sort | uniq -c | sort -n)
  else
    res=$(git log --name-only --since="$1" --author="$author" --pretty=format: $(git ls-files) | sed '/^\s*$/d' | sort | uniq -c | sort -n)
  fi
  if [ ! -z "$res" ]; then
    num_authors=$((num_authors+1))
    echo
    echo
    echo "$author"
    echo '--------------------------------------------------------------------------------'
    echo "$res"
  fi
done <<< "$(printf "$all_authors")"

printf '\n'
printf 'There are %s authors in total\n' "$num_authors"
