#!/bin/bash

for dir in $(locate "/.git" | grep -e "\.git$" | sed "s|/\.git$||")
do
  if [[ -d $dir ]]; then
    cd $dir
    if git rev-parse --git-dir > /dev/null 2>&1; then

      log=$(git log --pretty=format:"%h %<(14,trunc)%Cgreen%cr%Creset %s" --remotes --branches --since=6.months.ago $@ 2>/dev/null)

      if [ -n "$log" ]; then
        echo
        echo $(printf "\e[1;30m" && basename $dir && printf " \e[0;35m$dir\e[0m")
        echo "$log"
      fi
    fi
  fi
done
